### PR TITLE
.travis.yml: Add '-set_exit_status' to golint invocation

### LINKED ISSUE #26: travis: golint is not returning non-zero

### LINKED ISSUE #27: rules: failing golint
```
rules/danglingwhitespace/rule.go:22:1: exported function ValidateDanglingWhitespace should have comment or be unexported
```

### PR DESCRIPTION
**Pull request by wking**
So Travis tells us when golint finds something suspicious.

Fixes #26.
Fixes #27.

### CODE REVIEW

**Comment by vbatts** [comment]
https://github.com/vbatts/git-validation/issues/27 will also be needed before this. likely. And actively trying to get to the bottom of https://github.com/vbatts/git-validation/issues/24 :-\

**Comment by wking** [comment]
On Thu, Apr 27, 2017 at 10:30:35AM -0700, v1.0.0.batts wrote:
> https://github.com/vbatts/git-validation/issues/27 will also be
> needed before this.

No, you only need that to get local-branch PR's passing ;).  Since my
branch is in an external repo, it only has ‘pr’ tests.

> And actively trying to get to the bottom of
> https://github.com/vbatts/git-validation/issues/24 :-\

Will do.

**Comment by wking** [comment]
Oops, flipped those around.  I'll work on #27 but am not affected by #24.

**Comment by wking** [comment]
I've pushed b4e2a47 → 094999a to fix #27 too.

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
